[env]
board = "arduino:avr:nano"

[upload]
protocol = "serial"
speed = 9600
resetmethod = "ck"
upload_port = "/dev/ttyUSB0"

[run]
command = "arduino-cli compile --fqbn arduino:avr:nano {build.source_path} && arduino-cli upload -p {upload.upload_port} --fqbn arduino:avr:nano {build.source_path}"
